server:
  port: 7777
spring:
  redis:
    host: ${REDIS_HOST}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB}?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB
  mail:
    host: smtp.126.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
      from: ${MAIL_USERNAME}
      to: ${TO_MAIL}
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mybatis/mapper/*.xml

logging:
  level:
    root: debug

